- name: Deploy Dockerized Flask App from ECR
  hosts: proxy
  become: true
  become_method: sudo
  become_user: root
  tasks:

    - name: Login to Amazon ECR (Private)
      shell: |
        aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 257394496890.dkr.ecr.us-west-2.amazonaws.com
      register: ecr_login_result
      changed_when: false
      ignore_errors: true

    - name: Stop and Remove Existing Container (if running)
      shell: |
        docker stop ECR-Container || true
        docker rm ECR-Container || true
      ignore_errors: true

    - name: Pull Docker Image from Private ECR
      command: docker pull 257394496890.dkr.ecr.us-west-2.amazonaws.com/my-app:latest

    - name: Run Docker Container with Latest Image
      command: docker run -d --name ECR-Container -p 80:80 257394496890.dkr.ecr.us-west-2.amazonaws.com/my-app:latest