name: Build AWS Infra and Deploy Docker Image

on:
  workflow_dispatch:
    inputs:
      trigger:
        description: "apply OR destroy"
        required: true
        default: apply
        type: choice
        options:
          - apply
          - destroy

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-west-2
  ECR_REGISTRY: 257394496890.dkr.ecr.us-west-2.amazonaws.com
  ECR_REPOSITORY: my-app
  IMAGE_TAG: latest
  TRIGGER: ${{ inputs.trigger }}

jobs:
  deploy:
    name: Deploy with Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

     - name: Login to AWS ECR
       if: env.TRIGGER == 'apply'
       uses: aws-actions/amazon-ecr-login@v1
       with:
      region: us-west-2

    - name: Build and Push Docker Image to ECR
      if: env.TRIGGER == 'apply'
      run: |
        docker build -t $ECR_REPOSITORY .
        docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Terraform Init
      run: terraform init
      working-directory: ./Terraform

    - name: Terraform Format Check
      run: terraform fmt -check -recursive
      working-directory: ./Terraform

    - name: Terraform ${{ env.TRIGGER }}
      run: |
        terraform $TRIGGER \
          -var="public_key=$EC2_PUBLIC_SSH_KEY" \
          -var="key_name=ssh_key_aws" \
          -auto-approve
      working-directory: ./Terraform
