name: Deploy AWS Infra with Terraform & Ansible

on:
  push:
    branches:
      - main
    paths:
      - 'infra/'
  workflow_dispatch:   # 👈 this line enables manual run button

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: your-ecr-repo-name
  TF_WORK_DIR: Terraform
  TRIGGER: apply

jobs:
  deploy:
    name: Terraform + Docker + Ansible Deployment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0

    - name: Terraform Init
      run: terraform -chdir=$TF_WORK_DIR init

    - name: Terraform Apply
      run: terraform -chdir=$TF_WORK_DIR apply -auto-approve

    - name: Extract EC2 Private IP
      id: get_ip
      run: |
        PRIVATE_IP=$(terraform -chdir=$TF_WORK_DIR output -raw application_private_ip_1)
        echo "EC2_PRIVATE_IP=$PRIVATE_IP" >> $GITHUB_ENV

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        docker build -t $ECR_REPOSITORY:latest .
        docker tag $ECR_REPOSITORY:latest ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

    - name: Push Docker image to ECR
      run: |
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

    - name: SSH into EC2 & Deploy with Ansible
      if: env.TRIGGER == 'apply'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.EC2_PRIVATE_IP }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          sudo yum install -y ansible
          cd /home/ec2-user/your-app-folder
          ansible-playbook deploy.yml
